/**
 * generated by Xtext
 */
package org.xtext.edinburgh.ui.contentassist;

import org.xtext.edinburgh.ui.contentassist.AbstractPalomaProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class PalomaProposalProvider extends AbstractPalomaProposalProvider {
}
