/*
 * generated by Xtext
 */
package org.xtext.edinburgh.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.edinburgh.ui.internal.PalomaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PalomaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PalomaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PalomaActivator.getInstance().getInjector(PalomaActivator.ORG_XTEXT_EDINBURGH_PALOMA);
	}
	
}
