/*
 * generated by Xtext
 */
package org.xtext.edinburgh.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PalomaUiModule extends org.xtext.edinburgh.ui.AbstractPalomaUiModule {
	public PalomaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
