/*
* generated by Xtext
*/
package org.xtext.edinburgh.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.edinburgh.services.PalomaGrammarAccess;

public class PalomaParser extends AbstractContentAssistParser {
	
	@Inject
	private PalomaGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.edinburgh.ui.contentassist.antlr.internal.InternalPalomaParser createParser() {
		org.xtext.edinburgh.ui.contentassist.antlr.internal.InternalPalomaParser result = new org.xtext.edinburgh.ui.contentassist.antlr.internal.InternalPalomaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getACTIONAccess().getAlternatives(), "rule__ACTION__Alternatives");
					put(grammarAccess.getIRangeAccess().getAlternatives(), "rule__IRange__Alternatives");
					put(grammarAccess.getTerminal_PR_ExprAccess().getAlternatives(), "rule__Terminal_PR_Expr__Alternatives");
					put(grammarAccess.getTerminal_PR_ExprAccess().getAlternatives_1(), "rule__Terminal_PR_Expr__Alternatives_1");
					put(grammarAccess.getTerminal_RATE_ExprAccess().getAlternatives(), "rule__Terminal_RATE_Expr__Alternatives");
					put(grammarAccess.getTerminal_RATE_ExprAccess().getAlternatives_1(), "rule__Terminal_RATE_Expr__Alternatives_1");
					put(grammarAccess.getDistAccess().getAlternatives_2(), "rule__Dist__Alternatives_2");
					put(grammarAccess.getDistAccess().getAlternatives_4(), "rule__Dist__Alternatives_4");
					put(grammarAccess.getMATH_OPAccess().getAlternatives(), "rule__MATH_OP__Alternatives");
					put(grammarAccess.getNUMBERAccess().getAlternatives(), "rule__NUMBER__Alternatives");
					put(grammarAccess.getTerminal_Math_ExprAccess().getAlternatives(), "rule__Terminal_Math_Expr__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getParamAccess().getGroup(), "rule__Param__Group__0");
					put(grammarAccess.getAgentStateAccess().getGroup(), "rule__AgentState__Group__0");
					put(grammarAccess.getAgentStateAccess().getGroup_3(), "rule__AgentState__Group_3__0");
					put(grammarAccess.getPrefixAccess().getGroup(), "rule__Prefix__Group__0");
					put(grammarAccess.getACT_SpNoMsgAccess().getGroup(), "rule__ACT_SpNoMsg__Group__0");
					put(grammarAccess.getACT_SpBrAccess().getGroup(), "rule__ACT_SpBr__Group__0");
					put(grammarAccess.getACT_SpUniAccess().getGroup(), "rule__ACT_SpUni__Group__0");
					put(grammarAccess.getACT_InBrAccess().getGroup(), "rule__ACT_InBr__Group__0");
					put(grammarAccess.getACT_InUniAccess().getGroup(), "rule__ACT_InUni__Group__0");
					put(grammarAccess.getIRangeAccess().getGroup_2(), "rule__IRange__Group_2__0");
					put(grammarAccess.getIRangeAccess().getGroup_3(), "rule__IRange__Group_3__0");
					put(grammarAccess.getIRangeAccess().getGroup_3_1(), "rule__IRange__Group_3_1__0");
					put(grammarAccess.getPR_ExprAccess().getGroup(), "rule__PR_Expr__Group__0");
					put(grammarAccess.getPR_ExprAccess().getGroup_1(), "rule__PR_Expr__Group_1__0");
					put(grammarAccess.getTerminal_PR_ExprAccess().getGroup_0(), "rule__Terminal_PR_Expr__Group_0__0");
					put(grammarAccess.getRATE_ExprAccess().getGroup(), "rule__RATE_Expr__Group__0");
					put(grammarAccess.getRATE_ExprAccess().getGroup_1(), "rule__RATE_Expr__Group_1__0");
					put(grammarAccess.getTerminal_RATE_ExprAccess().getGroup_0(), "rule__Terminal_RATE_Expr__Group_0__0");
					put(grammarAccess.getDistAccess().getGroup(), "rule__Dist__Group__0");
					put(grammarAccess.getAGENT_NUMAccess().getGroup(), "rule__AGENT_NUM__Group__0");
					put(grammarAccess.getPOPULATIONAccess().getGroup(), "rule__POPULATION__Group__0");
					put(grammarAccess.getPOPULATIONAccess().getGroup_1(), "rule__POPULATION__Group_1__0");
					put(grammarAccess.getAGENTSAccess().getGroup(), "rule__AGENTS__Group__0");
					put(grammarAccess.getAGENTSAccess().getGroup_1(), "rule__AGENTS__Group_1__0");
					put(grammarAccess.getLOCAccess().getGroup(), "rule__LOC__Group__0");
					put(grammarAccess.getAGENTAccess().getGroup(), "rule__AGENT__Group__0");
					put(grammarAccess.getMATH_ExprAccess().getGroup(), "rule__MATH_Expr__Group__0");
					put(grammarAccess.getMATH_ExprAccess().getGroup_1(), "rule__MATH_Expr__Group_1__0");
					put(grammarAccess.getTerminal_Math_ExprAccess().getGroup_0(), "rule__Terminal_Math_Expr__Group_0__0");
					put(grammarAccess.getModelAccess().getParamsAssignment_1(), "rule__Model__ParamsAssignment_1");
					put(grammarAccess.getModelAccess().getStatesAssignment_3(), "rule__Model__StatesAssignment_3");
					put(grammarAccess.getModelAccess().getPopulationAssignment_5(), "rule__Model__PopulationAssignment_5");
					put(grammarAccess.getParamAccess().getNameAssignment_1(), "rule__Param__NameAssignment_1");
					put(grammarAccess.getParamAccess().getValueAssignment_3(), "rule__Param__ValueAssignment_3");
					put(grammarAccess.getAgentStateAccess().getNameAssignment_0(), "rule__AgentState__NameAssignment_0");
					put(grammarAccess.getAgentStateAccess().getPrefixsAssignment_2(), "rule__AgentState__PrefixsAssignment_2");
					put(grammarAccess.getAgentStateAccess().getPrefixsAssignment_3_1(), "rule__AgentState__PrefixsAssignment_3_1");
					put(grammarAccess.getPrefixAccess().getActionAssignment_0(), "rule__Prefix__ActionAssignment_0");
					put(grammarAccess.getPrefixAccess().getContinueAssignment_1(), "rule__Prefix__ContinueAssignment_1");
					put(grammarAccess.getACT_SpNoMsgAccess().getNameAssignment_1(), "rule__ACT_SpNoMsg__NameAssignment_1");
					put(grammarAccess.getACT_SpNoMsgAccess().getRateAssignment_3(), "rule__ACT_SpNoMsg__RateAssignment_3");
					put(grammarAccess.getACT_SpBrAccess().getNameAssignment_1(), "rule__ACT_SpBr__NameAssignment_1");
					put(grammarAccess.getACT_SpBrAccess().getRateAssignment_3(), "rule__ACT_SpBr__RateAssignment_3");
					put(grammarAccess.getACT_SpBrAccess().getRangeAssignment_7(), "rule__ACT_SpBr__RangeAssignment_7");
					put(grammarAccess.getACT_SpUniAccess().getNameAssignment_1(), "rule__ACT_SpUni__NameAssignment_1");
					put(grammarAccess.getACT_SpUniAccess().getRateAssignment_3(), "rule__ACT_SpUni__RateAssignment_3");
					put(grammarAccess.getACT_SpUniAccess().getRangeAssignment_7(), "rule__ACT_SpUni__RangeAssignment_7");
					put(grammarAccess.getACT_InBrAccess().getNameAssignment_1(), "rule__ACT_InBr__NameAssignment_1");
					put(grammarAccess.getACT_InBrAccess().getRateAssignment_3(), "rule__ACT_InBr__RateAssignment_3");
					put(grammarAccess.getACT_InBrAccess().getValueAssignment_7(), "rule__ACT_InBr__ValueAssignment_7");
					put(grammarAccess.getACT_InUniAccess().getNameAssignment_1(), "rule__ACT_InUni__NameAssignment_1");
					put(grammarAccess.getACT_InUniAccess().getRateAssignment_3(), "rule__ACT_InUni__RateAssignment_3");
					put(grammarAccess.getACT_InUniAccess().getValueAssignment_7(), "rule__ACT_InUni__ValueAssignment_7");
					put(grammarAccess.getPR_ExprAccess().getPrEAssignment_0(), "rule__PR_Expr__PrEAssignment_0");
					put(grammarAccess.getPR_ExprAccess().getPrEAssignment_1_1(), "rule__PR_Expr__PrEAssignment_1_1");
					put(grammarAccess.getTerminal_PR_ExprAccess().getLinkedParamAssignment_1_1(), "rule__Terminal_PR_Expr__LinkedParamAssignment_1_1");
					put(grammarAccess.getRATE_ExprAccess().getRtAssignment_0(), "rule__RATE_Expr__RtAssignment_0");
					put(grammarAccess.getRATE_ExprAccess().getRtAssignment_1_1(), "rule__RATE_Expr__RtAssignment_1_1");
					put(grammarAccess.getTerminal_RATE_ExprAccess().getLinkedParamAssignment_1_1(), "rule__Terminal_RATE_Expr__LinkedParamAssignment_1_1");
					put(grammarAccess.getAGENT_NUMAccess().getTypeAssignment_1(), "rule__AGENT_NUM__TypeAssignment_1");
					put(grammarAccess.getPOPULATIONAccess().getPopuAssignment_0(), "rule__POPULATION__PopuAssignment_0");
					put(grammarAccess.getPOPULATIONAccess().getPopuAssignment_1_1(), "rule__POPULATION__PopuAssignment_1_1");
					put(grammarAccess.getAGENTSAccess().getTypeAssignment_0(), "rule__AGENTS__TypeAssignment_0");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.edinburgh.ui.contentassist.antlr.internal.InternalPalomaParser typedParser = (org.xtext.edinburgh.ui.contentassist.antlr.internal.InternalPalomaParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public PalomaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PalomaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
