/*
* generated by Xtext
*/
package org.xtext.edinburgh.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.edinburgh.services.PalomaGrammarAccess;

public class PalomaParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PalomaGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.edinburgh.parser.antlr.internal.InternalPalomaParser createParser(XtextTokenStream stream) {
		return new org.xtext.edinburgh.parser.antlr.internal.InternalPalomaParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public PalomaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PalomaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
