/*
* generated by Xtext
*/
package org.xtext.edinburgh;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PalomaUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.edinburgh.ui.internal.PalomaActivator.getInstance().getInjector("org.xtext.edinburgh.Paloma");
	}
	
}
