/*
* generated by Xtext
*/
package org.xtext.edinburgh;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PalomaStandaloneSetup extends PalomaStandaloneSetupGenerated{

	public static void doSetup() {
		new PalomaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

